project_id = "qecpaduxewgnumrjrroo"

[functions.process-leagues]
verify_jwt = false

[functions.send-study-tip]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.trigger-email]
verify_jwt = false
